export { default as ContactInfo } from './contactInfo'
export { default as Education } from './education'
export { default as Employment } from './employment'
export { default as PersonalInfo } from './personalInfo'
export { default as Skill } from './skills'